version: '3.8'

services:
  web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 --timeout 600 manage:app
    volumes:
      - static_volume:/home/app/web/eveme/static
    expose:
      - 5000
    env_file:
      - ./.env.prod
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/eveme/static
    ports:
      - 1337:80
    depends_on:
      - web
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass h192hs1j2s1972d018us1jh2
    volumes: 
      - cache:/data
    depends_on:
      - web

volumes:
  static_volume:
  cache:
    driver: local