version: '3'
services:
  eveme:
    container_name: flask-container
    build: .
    entrypoint: python __init__.py
    env_file:
      - .env
    ports:
      - '5000:5000'
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"